package com.ezreb.htmlEditor.css;

public enum Style {

	COLOR("color", "Sets the color of text"),
	OPACITY("opacity", "Sets the opacity level for an element"),
	BACKGROUND("background", "Sets all the background properties in one declaration"),
	BACKGROUND_ATTACHMENT("background-attachment", "Sets whether a background image is fixed or scrolls with the rest of the page"),
	BACKGROUND_COLOR("background-color", "Sets the background color of an element"),
	BACKGROUND_IMAGE("background-image", "Sets the background image for an element"),
	BACKGROUND_POSITION("background-position", "Sets the starting position of a background image"),
	BACKGROUND_REPEAT("background-repeat", "Sets how a background image will be repeated"),
	BACKGROUND_CLIP("background-clip", "Specifies the painting area of the background"),
	BACKGROUND_ORIGIN("background-origin", "Specifies the positioning area of the background images"),
	BORDER("border", "Sets all the border properties in one declaration"),
	BORDER_BOTTOM("border-bottom", "Sets all the bottom border properties in one declaration"),
	BORDER_BOTTOM_COLOR("border-bottom-color", "Sets the color of the bottom border"),
	BORDER_BOTTOM_LEFT_RADIUS("border-bottom-left-radius", "Defines the shape of the border of the bottom-left corner"),
	BORDER_BOTTOM_RIGHT_RADIUS("border-bottom-right-radius", "Defines the shape of the border of the bottom-right corner"),
	BORDER_BOTTOM_STYLE("border-bottom-style", "Sets the style of the bottom border"),
	BORDER_BOTTOM_WIDTH("border-bottom-width", "Sets the width of the bottom border"),
	BORDER_COLOR("border-color", "Sets the color of the four borders"),
	BORDER_IMAGE("border-image", "A shorthand property for setting all the border-image-* properties"),
	BORDER_IMAGE_OUTSET("border-image-outset", "Specifies the amount by which the border image area extends beyond the border box"),
	BORDER_IMAGE_REPEAT("border-image-repeat", "Specifies whether the image-border should be repeated, rounded or stretched"),
	BORDER_IMAGE_SLICE("border-image-slice", "Specifies the inward offsets of the image-border"),
	BORDER_IMAGE_SOURCE("border-image-source", "Specifies an image to be used as a border"),
	BORDER_IMAGE_WIDTH("border-image-width", "Specifies the widths of the image-border"),
	BORDER_LEFT("border-left", "Sets all the left border properties in one declaration"),
	BORDER_LEFT_COLOR("border-left-color", "Sets the color of the left border"),
	BORDER_LEFT_STYLE("border-left-style", "Sets the style of the left border"),
	BORDER_LEFT_WIDTH("border-left-width", "Sets the width of the left border"),
	BORDER_RADIUS("border-radius", "A shorthand property for setting all the four border-*-radius properties"),
	BORDER_RIGHT("border-right", "Sets all the right border properties in one declaration"),
	BORDER_RIGHT_COLOR("border-right-color", "Sets the color of the right border"),
	BORDER_RIGHT_STYLE("border-right-style", "Sets the style of the right border"),
	BORDER_RIGHT_WIDTH("border-right-width", "Sets the width of the right border"),
	BORDER_STYLE("border-style", "Sets the style of the four borders"),
	BORDER_TOP("border-top", "Sets all the top border properties in one declaration"),
	BORDER_TOP_COLOR("border-top-color", "Sets the color of the top border"),
	BORDER_TOP_LEFT_RADIUS("border-top-left-radius", "Defines the shape of the border of the top-left corner"),
	BORDER_TOP_RIGHT_RADIUS("border-top-right-radius", "Defines the shape of the border of the top-right corner"),
	BORDER_TOP_STYLE("border-top-style", "Sets the style of the top border"),
	BORDER_TOP_WIDTH("border-top-width", "Sets the width of the top border"),
	BORDER_WIDTH("border-width", "Sets the width of the four borders"),
	BOX_DECORATION_BREAK("box-decoration-break", "Sets the behaviour of the background and border of an element at page-break, or, for in-line elements, at line-break."),
	BOX_SHADOW("box-shadow", "Attaches one or more drop-shadows to the box"),
	BOTTOM("bottom", "Specifies the bottom position of a positioned element"),
	CLEAR("clear", "Specifies which sides of an element where other floating elements are not allowed"),
	CLIP("clip", "Clips an absolutely positioned element"),
	DISPLAY("display", "Specifies how a certain HTML element should be displayed"),
	FLOAT("float", "Specifies whether or not a box should float"),
	HEIGHT("height", "Sets the height of an element"),
	LEFT("left", "Specifies the left position of a positioned element"),
	OVERFLOW("overflow", "Specifies what happens if content overflows an element's box"),
	OVERFLOW_X("overflow-x", "Specifies whether or not to clip the left/right edges of the content, if it overflows the element's content area"),
	OVERFLOW_Y("overflow-y", "Specifies whether or not to clip the top/bottom edges of the content, if it overflows the element's content area"),
	PADDING("padding", "Sets all the padding properties in one declaration"),
	PADDING_BOTTOM("padding-bottom", "Sets the bottom padding of an element"),
	PADDING_LEFT("padding-left", "Sets the left padding of an element"),
	PADDING_RIGHT("padding-right", "Sets the right padding of an element"),
	PADDING_TOP("padding-top", "Sets the top padding of an element"),
	POSITION("position", "Specifies the type of positioning method used for an element (static, relative, absolute or fixed)"),
	RIGHT("right", "Specifies the right position of a positioned element"),
	TOP("top", "Specifies the top position of a positioned element"),
	VISIBILITY("visibility", "Specifies whether or not an element is visible"),
	WIDTH("width", "Sets the width of an element"),
	VERTICAL_ALIGN("vertical-align", "Sets the vertical alignment of an element"),
	Z_INDEX("z-index", "Sets the stack order of a positioned element"),
	ALIGN_CONTENT("align-content", "Specifies the alignment between the lines inside a flexible container when the items do not use all available space."),
	ALIGN_ITEMS("align-items", "Specifies the alignment for items inside a flexible container."),
	ALIGN_SELF("align-self", "Specifies the alignment for selected items inside a flexible container."),
	FELX("flex", "Specifies the length of the item, relative to the rest"),
	FLEX_BASIS("flex-basis", "Specifies the initial length of a flexible item"),
	FLEX_DIRECTION("flex-direction", "Specifies the direction of the flexible items"),
	FLEX_FLOW("flex-flow", "A shorthand property for the flex-direction and the flex-wrap properties"),
	FLEX_GROW("flex-grow", "Specifies how much the item will grow relative to the rest"),
	FLEX_SHRINK("flex-shrink", "Specifies how the item will shrink relative to the rest"),
	FLEX_WRAP("flex-wrap", "Specifies whether the flexible items should wrap or not"),
	JUSTIFY_CONTENT("justify-content", "Specifies the alignment between the items inside a flexible container when the items do not use all available space."),
	MARGIN("margin", "Sets all the margin properties in one declaration"),
	MARGIN_BOTTOM("margin-bottom", "Sets the bottom margin of an element"),
	MARGIN_LEFT("margin-left", "Sets the left margin of an element"),
	MARGIN_RIGHT("margin-right", "Sets the right margin of an element"),
	MARGIN_TOP("margin-top", "Sets the top margin of an element"),
	MAX_HEIGHT("max-height", "Sets the maximum height of an element"),
	MAX_WIDTH("max-width", "Sets the maximum width of an element"),
	MIN_HEIGHT("min-height", "Sets the minimum height of an element"),
	MIN_WIDTH("min-width", "Sets the minimum width of an element"),
	ORDER("order", "Sets the order of the flexible item, relative to the rest"),
	HANGING_PUNCTUATION("hanging-punctuation", "Specifies whether a punctuation character may be placed outside the line box"),
	HYPHENS("hyphens", "Sets how to split words to improve the layout of paragraphs"),
	LETTER_SPACING("letter-spacing", "Increases or decreases the space between characters in a text"),
	LINE_BREAK("line-break", "Specifies how/if to break lines"),
	LINE_HEIGHT("line-height", "Sets the line height"),
	OVERFLOW_WRAP("overflow-wrap", "Specifies whether or not the browser may break lines within words in order to prevent overflow (when a string is too long to fit its containing box)"),
	TAB_SIZE("tab-size", "Specifies the length of the tab-character"),
	TEXT_ALIGN("text-align", "Specifies the horizontal alignment of text"),
	TEXT_ALIGN_LAST("text-align-last", "Describes how the last line of a block or a line right before a forced line break is aligned when text-align is \"justify\""),
	TEXT_INDENT("text-indent", "Specifies the indentation of the first line in a text-block"),
	TEXT_JUSTIFY("text-justify", "Specifies the justification method used when text-align is \"justify\""),
	TEXT_TRANSFORM("text-transform", "Controls the capitalization of text"),
	WHITE_SPACE("white-space", "Speci-fies how white-space inside an element is handled"),
	WORD_BREAK("word-break", "Specifies line breaking rules for non-CJK scripts"),
	WORD_SPACING("word-spacing", "Increases or decreases the space between words in a text"),
	WORD_WRAP("word-wrap", "Allows long, unbreakable words to be broken and wrap to the next line"),
	TEXT_DECORATION("text-decoration", "Specifies the decoration added to text"),
	TEXT_DECORATION_COLOR("text-decoration-color", "Specifies the color of the text-decoration"),
	TEXT_DECORATION_LINE("text-decoration-line", "Specifies the type of line in a text-decoration"),
	TEXT_DECORATION_STYLE("text-decoration-style", "Specifies the style of the line in a text decoration"),
	TEXT_SHADOW("text-shadow", "Adds shadow to text"),
	TEXT_UNDERLINE_POSITION("text-underline-position", "Specifies the position of the underline which is set using the text-decoration property"),
	FONT_FACE("@font-face", "A rule that allows websites to download and use fonts other than the \"web-safe\" fonts"),
	FONT_FEATURE_VALUES("@font-feature-values", "Allows authors to use a common name in font-variant-alternate for feature activated differently in OpenType"),
	FONT("font", "Sets all the font properties in one declaration"),
	FONT_FAMILY("font-family", "Specifies the font family for text"),
	FONT_FEATURE_SETTINGS("font-feature-settings", "Allows control over advanced typographic features in OpenType fonts"),
	FONT_KERNING("font-kerning", "Controls the usage of the kerning information (how letters are spaced)"),
	FONT_LANGUAGE_OVERRIDE("font-language-override", "Controls the usage of language-specific glyphs in a typeface"),
	FONT_SIZE("font-size", "Specifies the font size of text"),
	FONT_SIZE_ADJUST("font-size-adjust", "Preserves the readability of text when font fallback occurs"),
	FONT_STRECH("font-stretch", "Selects a normal, condensed, or expanded face from a font family"),
	FONT_STYLE("font-style", "Specifies the font style for text"),
	FONT_SYNTHESIS("font-synthesis", "Controls which missing typefaces (bold or italic) may be synthesized by the browser"),
	FONT_VARIANT("font-variant", "Specifies whether or not a text should be displayed in a small-caps font"),
	FONT_VARIANT_ALTERNATES("font-variant-alternates", "Controls the usage of alternate glyphs associated to alternative names defined in @font-feature-values"),
	FONT_VARIANT_CAPS("font-variant-caps", "Controls the usage of alternate glyphs for capital letters"),
	FONT_VARIANT_EAST_ASIAN("font-variant-east-asian", "Controls the usage of alternate glyphs for East Asian scripts (e.g Japanese and Chinese)"),
	FONT_VARIANT_LIGATURES("font-variant-ligatures", "Controls which ligatures and contextual forms are used in textual content of the elements it applies to"),
	FONT_VARIANT_NUMERIC("font-variant-numeric", "Controls the usage of alternate glyphs for numbers, fractions, and ordinal markers"),
	FONT_VARIANT_POSITION("font-variant-position", "Controls the usage of alternate glyphs of smaller size positioned as superscript or subscript regarding the baseline of the font"),
	FONT_WEIGHT("font-weight", "Specifies the weight of a font"),
	DIRECTION("direction", "Specifies the text direction/writing direction"),
	TEXT_ORIENTATION("text-orientation", "Defines the orientation of the text in a line"),
	TEXT_COMBINE_UPRIGHT("text-combine-upright", "Specifies the combination of multiple characters into the space of a single character"),
	UNICODE_BIDI("unicode-bidi", "Used together with the direction property to set or return whether the text should be overridden to support multiple languages in the same document"),
	WRITING_MODE("writing-mode", ""),
	BORDER_COLLAPSE("border-collapse", "Specifies whether or not table borders should be collapsed"),
	BORDER_SPACING("border-spacing", "Specifies the distance between the borders of adjacent cells"),
	CAPTION_SIDE("caption-side", "Specifies the placement of a table caption"),
	EMPTY_CELLS("empty-cells", "Specifies whether or not to display borders and background on empty cells in a table"),
	TABLE_LAYOUT("table-layout", "Sets the layout algorithm to be used for a table"),
	COUNTER_INCREMENT("counter-increment", "Increments one or more counters"),
	COUNTER_RESET("counter-reset", "Creates or resets one or more counters"),
	LIST_STYLE("list-style", "Sets all the properties for a list in one declaration"),
	LIST_STYLE_IMAGE("list-style-image", "Specifies an image as the list-item marker"),
	LIST_STYLE_POSITION("list-style-position", "Specifies if the list-item markers should appear inside or outside the content flow"),
	LIST_STYLE_TYPE("list-style-type", "Specifies the type of list-item marker"),
	KEYFRAMES("@keyframes", "Specifies the animation"),
	ANIMATION("animation", "A shorthand property for all the animation properties below, except the animation-play-state property"),
	ANIMATION_DELAY("animation-delay", "Specifies when the animation will start"),
	ANIMATION_DIRECTION("animation-direction", "Specifies whether or not the animation should play in reverse on alternate cycles"),
	ANIMATION_DURATION("animation-duration", "Specifies how many seconds or milliseconds an animation takes to complete one cycle"),
	ANIMATION_FILL_MODE("animation-fill-mode", "Specifies what values are applied by the animation outside the time it is executing"),
	ANIMATION_ITERATION_COUNT("animation-iteration-count", "Specifies the number of times an animation should be played"),
	ANIMATION_NAME("animation-name", "Specifies a name for the @keyframes animation"),
	ANIMATION_TIMING_FUNCTION("animation-timing-function", "Specifies the speed curve of the animation"),
	ANIMATION_PLAY_STATE("animation-play-state", "Specifies whether the animation is running or paused"),
	BACKFACE_VISIBILITY("backface-visibility", "Defines whether or not an element should be visible when not facing the screen"),
	PERSPECTIVE("perspective", "Specifies the perspective on how 3D elements are viewed"),
	PERSPECTIVE_ORIGIN("perspective-origin", "Specifies the bottom position of 3D elements"),
	TRANSFORM("transform", "Applies a 2D or 3D transformation to an element"),
	TRANSFORM_ORIGIN("transform-origin", "Allows you to change the position on transformed elements"),
	TRANSFORM_STYLE("transform-style", "Specifies how nested elements are rendered in 3D space"),
	TRANSITION("transition", "A shorthand property for setting the four transition properties"),
	TRANSITION_PROPERTY("transition-property", "Specifies the name of the CSS property the transition effect is for"),
	TRANSITION_DURATION("transition-duration", "Specifies how many seconds or milliseconds a transition effect takes to complete"),
	TRANSITION_TIMING_FUNCTION("transition-timing-function", "Specifies the speed curve of the transition effect"),
	TRANSITION_DELAY("transition-delay", "Specifies when the transition effect will start"),
	BOX_SIZING("box-sizing", "Tells the browser what the sizing properties (width and height) should include"),
	CONTENT("content", "Used with the :before and :after pseudo-elements, to insert generated content"),
	CURSOR("cursor", "Specifies the type of cursor to be displayed"),
	ICON("icon", "Provides the author the ability to style an element with an iconic equivalent"),
	IME_MODE("ime-mode", "Controls the state of the input method editor for text fields"),
	NAV_DOWN("nav-down", "Specifies where to navigate when using the arrow-down navigation key"),
	NAV_INDEX("nav-index", "Specifies the tabbing order for an element"),
	NAV_LEFT("nav-left", "Specifies where to navigate when using the arrow-left navigation key"),
	NAV_RIGHT("nav-right", "Specifies where to navigate when using the arrow-right navigation key"),
	NAV_UP("nav-up", "Specifies where to navigate when using the arrow-up navigation key"),
	OUTLINE("outline", "Sets all the outline properties in one declaration"),
	OUTLINE_COLOR("outline-color", "Sets the color of an outline"),
	OUTLINE_OFFSET("outline-offset", "Offsets an outline, and draws it beyond the border edge"),
	OUTLINE_STYLE("outline-style", "Sets the style of an outline"),
	OUTLINE_WIDTH("outline-width", "Sets the width of an outline"),
	RESIZE("resize", "Specifies whether or not an element is resizable by the user"),
	TEXT_OVERFLOW("text-overflow", "Specifies what should happen when text overflows the containing element"),
	BREAK_AFTER("break-after", "Specifies the page-, column-, or region-break behavior after the generated box"),
	BREAK_BEFORE("break-before", "Specifies the page-, column-, or region-break behavior before the generated box"),
	BREAK_INSIDE("break-inside", "Specifies the page-, column-, or region-break behavior inside the generated box"),
	COLUMN_COUNT("column-count", "Specifies the number of columns an element should be divided into"),
	COLUMN_FILL("column-fill", "Specifies how to fill columns"),
	COLUMN_GAP("column-gap", "Specifies the gap between the columns"),
	COLUMN_RULE("column-rule", "A shorthand property for setting all the column-rule-* properties"),
	COLUMN_RULE_COLOR("column-rule-color", "Specifies the color of the rule between columns"),
	COLUMN_RULE_STYLE("column-rule-style", "Specifies the style of the rule between columns"),
	COLUMN_RULE_WIDTH("column-rule-width", "Specifies the width of the rule between columns"),
	COLUMN_SPAN("column-span", "Specifies how many columns an element should span across"),
	COLUMN_WIDTH("column-width", "Specifies the width of the columns"),
	COLUMNS("columns", "A shorthand property for setting column-width and column-count"),
	WINDOWS("widows", "Sets the minimum number of lines that must be left at the top of a page when a page break occurs inside an element");
	
	private String name;
	public final String description;
	private Style(String name, String description) {
		this.name = name;
		this.description = description;
	}
	/**
	 * @return the name of the style
	 */
	public String getName() {
		return name;
	}
	/**
	 * @return the description of the style
	 */
	public String getDescription() {
		return description;
	}
	
}
